### ISSUE TITLE
[Feature Request] Some examples that use the different `fromFactory` API's please ?

### ISSUE THREAD

**Issue by Smurf-IV** [tyanmahou/Emaject#1]

**Comment by tyanmahou** [comment]
Sorry for the late reply.
thank you.
I will try to prepare sample code soon.

**Comment by tyanmahou** [comment]
Hi @Smurf-IV .
Thank you for waiting.

 `fromFactory` method has 2 overload functions .

```cpp
auto fromFactory(const Factory<T>& factory) const;
auto fromFactory(const std::function<std::shared_ptr<T>()>& factory) const;
```
also, `Factory<T>` is an type alias for  `std::function<std::shared_ptr<T>(Container*)>`.

now, there is **not difference** in the behavior of these overloads.

if you want to use a `Container*` argument, you can use the former method.
but if not, you can use the latter.

----
by the way,
If you omit the `to()` method when binding, `toSelf()` is used.
```cpp
auto factory = []()->std::shared_ptr<IFoo> {
    return std::make_shared<Foo>();
};
c->bind<IFoo>()
    // Use .toSelf() => .to<IFoo>()
    .fromFactory(factory)
    .asCached();
```

----
SampleCode:
https://github.com/tyanmahou/Emaject/blob/main/Emaject/tests/from_factory.cpp

**Comment by Smurf-IV** [comment]
Great - thanks
