### ISSUE TITLE
[Feature Request] Some way of extracting a singleton object that has _already_ been created

### ISSUE THREAD

**Issue by Smurf-IV** [tyanmahou/Emaject#2]
I have the following situation:
- A `Config construct` has been read in to the running application (Unit test / dll / etc)
- I want it to be passed around `init` style functions that are taking a `emaject::Injector& injector` instance (i,e, another DI loaded dll that needs the instance of the exe's inject instance)
- In that DI loaded dll it needs access to the `Config Construct` to read out specific details of how to use itself or load further DI dll's.

So the problem is:
- It's a singleton that does not have an interface
- Already created by the host process
- how to inject into the `emaject::Injector` instance so that it can be retrieved further down the line

**Comment by Smurf-IV** [comment]
I think what I am looking for is something that demonstrates how to populate the `injector` so that the `fromInstance` API works

**Comment by tyanmahou** [comment]
Hi, @Smurf-IV 
I don't fully understand the situation yet, but it seems like the following?

```cpp
    struct SingletonInstaller : IInstaller
    {
        void onBinding(Container* c) const
        {
            c->bind<Singleton>()
                .toSelf()
                .fromInstance(Singleton::Instance())
                .asSingle();
        }
    };
```
https://github.com/tyanmahou/Emaject/blob/main/Emaject/tests/from_instance.cpp

`fromInstance` receives `shared_ptr<T>`  instance as an argument.
This is an API that uses the instance as is for resolving injection.

Therefore, when using a singleton that cannot be handled with `shared_ptr<T>`,
should be placed in a wrapper class

**Comment by Smurf-IV** [comment]
> should be placed in a wrapper class

That is what I ended up doing, just thought that might be an easier way.
Thanks for the answer
